apiVersion: batch/v1
kind: Job
metadata:
  name: start-argocd-syncing
  namespace: akuity
spec:
  template:
    spec:
      containers:
      - name: main
        image: docker/whalesay
        command: ["cowsay", "hello, argo cd is syncing"]
      restartPolicy: Never
  backoffLimit: 4
